server:
  port: 8085
  servlet:
    context-path: /stc
spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update